DEVICE_PATH := device/samsung/a40

# TEE sepolicy
BOARD_SEPOLICY_TEE_FLAVOR := teegris

# Inherit common board flags
include device/samsung/universal7904-common/BoardConfigCommon.mk

# Boot image
BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_CUSTOM_BOOTIMG := true

# DTB
BOARD_DTB_CFG := $(COMMON_PATH)/configs/kernel/exynos7904.cfg
BOARD_PACK_RADIOIMAGES += dtb.img

# DTBO
BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_DTBO_CFG := $(DEVICE_PATH)/configs/kernel/a40.cfg
BOARD_INCLUDE_RECOVERY_DTBO := true

# Init
TARGET_INIT_VENDOR_LIB := libinit_a40

# Kernel
TARGET_KERNEL_CONFIG := a40_defconfig

# Keymaster
TARGET_KEYMASTER_VARIANT := samsung

# LIBHWJPEG
BOARD_HWJPEG_ANDROID_VERSION := 11

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 37748736
BOARD_DTBIMG_PARTITION_SIZE := 8388608
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 55574528
BOARD_CACHEIMAGE_PARTITION_SIZE := 419430400
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5033164800
BOARD_VENDORIMAGE_PARTITION_SIZE := 629145600
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
# Not using product partition as SM-A405S' product
# partition is far too small (83886080 bytes)

BOARD_ROOT_EXTRA_FOLDERS := efs

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.exynos7904

# Security patch level
VENDOR_SECURITY_PATCH := 2023-03-01

# Releasetools
TARGET_RELEASETOOLS_EXTENSIONS := $(DEVICE_PATH)/releasetools

# Verified Boot
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --include_descriptors_from_image $(PRODUCT_OUT)/dtb.img
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1

# VINTF
DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/device_manifest.xml
